# This file was generated by GoReleaser. DO NOT EDIT.
cask "cthulhu-cli" do
  name "cthulhu-cli"
  desc "CLI for running agentic workflows in your repository"
  homepage "https://github.com/frunl/cthulhu-cli"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cthulhu"

  on_macos do
    on_intel do
      url "https://github.com/frunl/cthulhu-cli/releases/download/v#{version}/cthulhu_#{version}_darwin_amd64.tar.gz"
      sha256 "90b2202e99f24e039bd95314135245f36c73a93c9e305353884b2ab57a4242de"
    end
    on_arm do
      url "https://github.com/frunl/cthulhu-cli/releases/download/v#{version}/cthulhu_#{version}_darwin_arm64.tar.gz"
      sha256 "a6396366fcce15cfa9c9211083bf3bb883fb8a116622a26c3ae2b0aa12bb975e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frunl/cthulhu-cli/releases/download/v#{version}/cthulhu_#{version}_linux_amd64.tar.gz"
      sha256 "57f954e4864db97015cdd97879d6246e5ac4f3cf6a70ecd5dde7ce037ec2a216"
    end
    on_arm do
      url "https://github.com/frunl/cthulhu-cli/releases/download/v#{version}/cthulhu_#{version}_linux_arm64.tar.gz"
      sha256 "471c113105dde4e88eb54e914243ad87944c412c37435abf880c2bf07f0832d3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cthulhu"]
    end
  end

  # No zap stanza required
end
