# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CthulhuCli < Formula
  desc "CLI for running agentic workflows in your repository"
  homepage "https://github.com/frunl/cthulhu"
  version "0.8.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frunl/cthulhu/releases/download/v0.8.4/cthulhu_0.8.4_darwin_amd64.tar.gz"
      sha256 "c064918f2415af1d05959e163d652c5b199f7dba294bd3562360c372d5e75851"

      def install
        bin.install "cthulhu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frunl/cthulhu/releases/download/v0.8.4/cthulhu_0.8.4_darwin_arm64.tar.gz"
      sha256 "a9d2d57fb35c302c255bc04ac0c7c7b3f86e1e00c3a441e77e0869961b3bf926"

      def install
        bin.install "cthulhu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/cthulhu/releases/download/v0.8.4/cthulhu_0.8.4_linux_amd64.tar.gz"
      sha256 "1a37331945bf50224124d3e3d5da1c446ab001bef6c33fe2629d4e06ef340f62"
      def install
        bin.install "cthulhu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/cthulhu/releases/download/v0.8.4/cthulhu_0.8.4_linux_arm64.tar.gz"
      sha256 "0b2d98f1851de8b00b296e654d44634831f94c88af3e4047b97e7dfd8d8cb8ea"
      def install
        bin.install "cthulhu"
      end
    end
  end

  test do
    system "#{bin}/cthulhu", "--version"
  end
end
