# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CthulhuCli < Formula
  desc "CLI for running agentic workflows in your repository"
  homepage "https://github.com/frunl/cthulhu"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frunl/cthulhu/releases/download/v0.7.0/cthulhu_0.7.0_darwin_amd64.tar.gz"
      sha256 "6be2ba05fa41fb824ef67c4caa62f868144d8e58c026617895f07fdeb1ac9cee"

      def install
        bin.install "cthulhu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frunl/cthulhu/releases/download/v0.7.0/cthulhu_0.7.0_darwin_arm64.tar.gz"
      sha256 "5aea5c3ec18fa8e9f325d450c3fa6373dd8682fa32a90b0c3169f6bf0c7c7eb5"

      def install
        bin.install "cthulhu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/cthulhu/releases/download/v0.7.0/cthulhu_0.7.0_linux_amd64.tar.gz"
      sha256 "26fa8716a33c837b4adbd71714f192e1eb6a33a9195af0f6f322a53be8e709bf"
      def install
        bin.install "cthulhu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/cthulhu/releases/download/v0.7.0/cthulhu_0.7.0_linux_arm64.tar.gz"
      sha256 "891558e61707c9690082b3a06abc30faa2c6e2b41e2d483dbab5b356274befcf"
      def install
        bin.install "cthulhu"
      end
    end
  end

  test do
    system "#{bin}/cthulhu", "--version"
  end
end
