# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CthulhuCli < Formula
  desc "CLI for running agentic workflows in your repository"
  homepage "https://github.com/frunl/cthulhu"
  version "0.7.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frunl/cthulhu/releases/download/v0.7.3/cthulhu_0.7.3_darwin_amd64.tar.gz"
      sha256 "e025604568af19550ed06f9cba38ec83b54ea968a4d15438bf0f58efabce68f6"

      def install
        bin.install "cthulhu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frunl/cthulhu/releases/download/v0.7.3/cthulhu_0.7.3_darwin_arm64.tar.gz"
      sha256 "9fc0297ba0460000599135ed8c300be020f161d0ea5b214f567ccf601d9d91cf"

      def install
        bin.install "cthulhu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/cthulhu/releases/download/v0.7.3/cthulhu_0.7.3_linux_amd64.tar.gz"
      sha256 "56e675f2cd7eec7bae338f2116829152e52f5f570a810a243715a5bf5787e071"
      def install
        bin.install "cthulhu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/cthulhu/releases/download/v0.7.3/cthulhu_0.7.3_linux_arm64.tar.gz"
      sha256 "41d699613b53a8b49a7e3d929d3914c4ade02a56e26aa4efe422db8970d7a495"
      def install
        bin.install "cthulhu"
      end
    end
  end

  test do
    system "#{bin}/cthulhu", "--version"
  end
end
