# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrunlCli < Formula
  desc "CLI for running agentic workflows in your repository"
  homepage "https://github.com/frunl/frunl-cli"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frunl/frunl-cli/releases/download/v0.10.0/frunl_0.10.0_darwin_amd64.tar.gz"
      sha256 "d94a2818e30b2354b696c194f0c5eee2fe061d5defe8c371b332b9ec614cb94a"

      define_method(:install) do
        bin.install "frunl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frunl/frunl-cli/releases/download/v0.10.0/frunl_0.10.0_darwin_arm64.tar.gz"
      sha256 "b2da38629c55b6ca968349099effeda400f094dbab07b51b9d5807188cbd58f0"

      define_method(:install) do
        bin.install "frunl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/frunl-cli/releases/download/v0.10.0/frunl_0.10.0_linux_amd64.tar.gz"
      sha256 "3ac90eb142e4879e71698cd230fa81f54fe94f30e8544ff97caf7dfa8f28cdc0"
      define_method(:install) do
        bin.install "frunl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/frunl-cli/releases/download/v0.10.0/frunl_0.10.0_linux_arm64.tar.gz"
      sha256 "342c8e9177eb9d9d990929c57e174b158dc481a0a48795075711320a56a5e6de"
      define_method(:install) do
        bin.install "frunl"
      end
    end
  end

  test do
    system "#{bin}/frunl", "--version"
  end
end
