# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrunlCli < Formula
  desc "CLI for running agentic workflows in your repository"
  homepage "https://github.com/frunl/frunl-cli"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frunl/frunl-cli/releases/download/v0.11.0/frunl_0.11.0_darwin_amd64.tar.gz"
      sha256 "273047933c5057085af791ebe1c87129107c117f9f9e05f703c935f843e93196"

      define_method(:install) do
        bin.install "frunl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frunl/frunl-cli/releases/download/v0.11.0/frunl_0.11.0_darwin_arm64.tar.gz"
      sha256 "2dae9bcd7cd63223d8123e9b5f27a314e4ba6d16ac731c766a79c0b93dbe3e3d"

      define_method(:install) do
        bin.install "frunl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/frunl-cli/releases/download/v0.11.0/frunl_0.11.0_linux_amd64.tar.gz"
      sha256 "14a21a526f723949afa63fff49976d3a41a954f8abcbf2599759f9004d3e2ce8"
      define_method(:install) do
        bin.install "frunl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frunl/frunl-cli/releases/download/v0.11.0/frunl_0.11.0_linux_arm64.tar.gz"
      sha256 "32ea56b0f395e2cacac13888529a4b50e034145b9267122d72ff7a22b9de4d1c"
      define_method(:install) do
        bin.install "frunl"
      end
    end
  end

  test do
    system "#{bin}/frunl", "--version"
  end
end
